# Source: cluster-api-aws/templates/cluster.yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: e6c61b1f-3f7b-45a9-a3c1-aa7d36199d61
  namespace: e6c61b1f-3f7b-45a9-a3c1-aa7d36199d61
spec:
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AWSCluster
    name: e6c61b1f-3f7b-45a9-a3c1-aa7d36199d61
  controlPlaneRef:
    kind: KubeadmControlPlane
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    name: "e6c61b1f-3f7b-45a9-a3c1-aa7d36199d61-control-plane"
